import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next dApp</title>
      <meta name="description" content="Generated by create-next-dapp" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <span>create-next-dapp</span>
    </main>
  </>
);

export default Home;
