import Head from 'next/head';
import type { NextPage } from 'next';
import { useState, useEffect } from 'react';
import { ethers } from 'ethers';
import type { Greeter } from '../types/contracts';
import GreeterArtifact from '../../artifacts/src/contracts/Greeter.sol/Greeter.json';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [greeting, setGreeting] = useState('');
  const [newGreeting, setNewGreeting] = useState('');
  const [provider, setProvider] = useState<ethers.providers.Web3Provider>();

  // npx hardhat run --network localhost src/scripts/deploy.ts
  const contractAddress = '0x5FbDB2315678afecb367f032d93F642f64180aa3';

  const fetchGreeting = async () => {
    const contract = new ethers.Contract(contractAddress, GreeterArtifact.abi, provider) as Greeter;

    try {
      const _greeting = await contract.greet();
      setGreeting(_greeting);
    } catch (error) {
      console.error(error);
    }
  };

  const updateGreeting = async () => {
    const signer = provider?.getSigner();
    const contract = new ethers.Contract(contractAddress, GreeterArtifact.abi, signer) as Greeter;

    try {
      const setGreetingTx = await contract.setGreeting(newGreeting);
      await setGreetingTx.wait();
    } catch (error) {
      console.error(error);
    }

    setNewGreeting('');
  };

  useEffect(() => {
    window.ethereum.request({ method: 'eth_requestAccounts' });
    setProvider(new ethers.providers.Web3Provider(window.ethereum as any));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next dApp</title>
        <meta name="description" content="Generated by create-next-dapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <h1>create-next-dapp</h1>
        <h3>
          Greeting: <span className={styles.greeting}>{greeting}</span>
        </h3>
        <input
          type="text"
          value={newGreeting}
          placeholder="My new greeting!"
          onChange={(event) => setNewGreeting(event.target.value)}
        />
        <div>
          <button onClick={fetchGreeting}>Fetch Greeting</button>
          <button onClick={updateGreeting}>Set Greeting</button>
        </div>
      </main>
    </>
  );
};

export default Home;
